/**
 * Vitest config — @cloudflare/vitest-pool-workers ≥0.18 Vite-plugin form (same
 * setup as workers/sync-hub). Tests import their APIs from "cloudflare:test".
 *
 * D1: migrations/ is read here (Node side) and applied inside the Workers
 * runtime by test/apply-migrations.ts (the standard readD1Migrations +
 * applyD1Migrations pattern).
 *
 * Module aliases: the `cmem-repo-modules` plugin applies build/aliases.mjs —
 * the SAME config scripts/build.mjs applies for `wrangler deploy` — so tests
 * run the bundle graph production runs (logger shim, recall MCP alias, bare
 * packages resolved from this package's node_modules).
 *
 * Outbound fetch: miniflare's `outboundService` intercepts every fetch the
 * Worker makes. `mockOutbound` fakes the three LLM providers (see
 * mockLlmResponse for the behaviour switches); anything else is a 599.
 */

import { cloudflareTest, readD1Migrations } from '@cloudflare/vitest-pool-workers';
import { readdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { Plugin } from 'vite';
import { defineConfig } from 'vitest/config';
// Plain .mjs shared with scripts/build.mjs (typed via allowJs).
import { BARE_ALIASES, PACKAGE_ROOT, REPO_ROOT, isBareSpecifier, isOutsidePackage, shimFor } from './build/aliases.mjs';

const aliases = BARE_ALIASES as Record<string, string>;

const repoModulesPlugin: Plugin = {
	name: 'cmem-repo-modules',
	enforce: 'pre',
	async resolveId(source, importer, options) {
		if (Object.hasOwn(aliases, source)) return aliases[source];
		if (!importer) return null;
		const importerPath = importer.split('?')[0]!;
		if (source.startsWith('.')) {
			return (shimFor(resolve(dirname(importerPath), source)) as string | null) ?? null;
		}
		// Repo files (outside this package) import zod / the MCP SDK; resolve
		// them as if imported from here, since the repo root may lack node_modules.
		if (isBareSpecifier(source) && isOutsidePackage(importerPath)) {
			return this.resolve(source, resolve(PACKAGE_ROOT, 'src/index.ts'), { ...options, skipSelf: true });
		}
		return null;
	},
};

// ─── LLM provider mocks ─────────────────────────────────────────────────────
//
// Behaviour is selected by the MODEL name (CLAUDE_MEM_SERVER_MODEL), so a test
// picks it by passing a modified env to scheduleGeneration()/runDueJobs():
//   (default)      valid XML: a <summary> for session-summary prompts, else one
//                  <observation> whose narrative echoes the first `marker-…`
//                  token found in the prompt (so tests can search for it)
//   mock-429       HTTP 429 (rate_limit, retryable)
//   mock-500       HTTP 500 (transient, retryable)
//   mock-400       HTTP 400 (unrecoverable)
//   mock-flaky     HTTP 503 on the first call per generation job, then success
//   mock-garbage   200 with text the parser rejects (parse_error)
//   mock-skip      <skip_summary/> (success, nothing recorded)
//   mock-multi     three observations
// Calls per generation job are counted so mock-flaky can fail exactly once.

const flakyCalls = new Map<string, number>();

function observationXml(marker: string, index = 0): string {
	return `<observation>
  <type>discovery</type>
  <title>Mock observation ${index} ${marker}</title>
  <subtitle>Generated by the test provider</subtitle>
  <facts><fact>The worker read a.ts (${marker})</fact></facts>
  <narrative>Narrative for ${marker}: the agent inspected configuration files.</narrative>
  <concepts><concept>how-it-works</concept></concepts>
  <files_read><file>a.ts</file></files_read>
  <files_modified></files_modified>
</observation>`;
}

function summaryXml(marker: string): string {
	return `<summary>
  <request>Summarize session ${marker}</request>
  <investigated>Looked at the ingest path</investigated>
  <learned>Summaries are persisted with kind summary (${marker})</learned>
  <completed>Wrote the summary</completed>
  <next_steps>Nothing</next_steps>
  <notes>none</notes>
</summary>`;
}

function mockLlmResponse(model: string, prompt: string): { status: number; text?: string; headers?: Record<string, string> } {
	const jobId = /<generation_job_id>([^<]+)<\/generation_job_id>/.exec(prompt)?.[1] ?? 'unknown';
	const marker = /marker-[A-Za-z0-9-]+/.exec(prompt)?.[0] ?? 'no-marker';
	const isSummary = prompt.includes('You are reviewing a complete agent session');
	switch (model) {
		case 'mock-429':
			return { status: 429, text: '{"error":{"type":"rate_limit_error","message":"slow down"}}', headers: { 'retry-after': '1' } };
		case 'mock-500':
			return { status: 500, text: '{"error":{"type":"api_error","message":"internal"}}' };
		case 'mock-400':
			return { status: 400, text: '{"error":{"type":"invalid_request_error","message":"bad request"}}' };
		case 'mock-flaky': {
			const calls = (flakyCalls.get(jobId) ?? 0) + 1;
			flakyCalls.set(jobId, calls);
			if (calls === 1) return { status: 503, text: 'upstream unavailable' };
			break;
		}
		case 'mock-garbage':
			return { status: 200, text: 'I am not XML at all' };
		case 'mock-skip':
			return { status: 200, text: '<skip_summary reason="trivial" />' };
		case 'mock-multi':
			return { status: 200, text: [0, 1, 2].map((i) => observationXml(marker, i)).join('\n') };
	}
	return { status: 200, text: isSummary ? summaryXml(marker) : observationXml(marker) };
}

async function mockLlm(provider: 'claude' | 'gemini' | 'openrouter', request: Request, url: URL): Promise<Response> {
	const body = (await request.json()) as Record<string, any>;
	const model = provider === 'gemini' ? decodeURIComponent(/models\/([^:]+):/.exec(url.pathname)?.[1] ?? '') : String(body.model ?? '');
	const prompt: string =
		provider === 'gemini' ? String(body.contents?.[0]?.parts?.[0]?.text ?? '') : String(body.messages?.[0]?.content ?? '');
	const out = mockLlmResponse(model, prompt);
	if (out.status !== 200) {
		return new Response(out.text ?? '', { status: out.status, headers: out.headers });
	}
	const text = out.text ?? '';
	const payload =
		provider === 'claude'
			? { content: [{ type: 'text', text }], usage: { input_tokens: 10, output_tokens: 20 } }
			: provider === 'gemini'
				? { candidates: [{ content: { parts: [{ text }] } }], usageMetadata: { totalTokenCount: 30 } }
				: { choices: [{ message: { content: text } }], usage: { total_tokens: 30 } };
	return Response.json(payload);
}

async function mockOutbound(request: Request): Promise<Response> {
	const url = new URL(request.url);
	if (request.method === 'POST') {
		if (url.hostname === 'api.anthropic.com' && url.pathname === '/v1/messages') return mockLlm('claude', request, url);
		if (url.hostname === 'generativelanguage.googleapis.com') return mockLlm('gemini', request, url);
		if (url.hostname === 'openrouter.ai' && url.pathname === '/api/v1/chat/completions') return mockLlm('openrouter', request, url);
	}
	return new Response(`unexpected outbound fetch in tests: ${request.method} ${request.url}`, { status: 599 });
}

export default defineConfig(async () => {
	const migrations = await readD1Migrations(resolve(PACKAGE_ROOT as string, 'migrations'));
	return {
		plugins: [
			repoModulesPlugin,
			cloudflareTest({
				// Source entry (wrangler.jsonc `main` points at the custom-build output).
				main: './src/index.ts',
				wrangler: { configPath: './wrangler.jsonc' },
				miniflare: {
					bindings: {
						TEST_MIGRATIONS: migrations,
						CMEM_ADMIN_TOKEN: 'test-admin-token',
						// No provider API keys here: without one, generation is
						// disabled and jobs stay `queued`, which the route/storage
						// tests rely on. test/generation.test.ts passes an env WITH
						// keys straight to the handlers.
						// Directory listing for the mode-registry completeness test.
						TEST_MODE_IDS: readdirSync(resolve(REPO_ROOT as string, 'plugin/modes'))
							.filter((f) => f.endsWith('.json'))
							.map((f) => f.slice(0, -'.json'.length)),
					},
					outboundService: mockOutbound,
				},
			}),
		],
		server: { fs: { allow: [REPO_ROOT as string] } },
		test: {
			setupFiles: ['./test/apply-migrations.ts'],
		},
	};
});
